import { AdminDashboardData } from './types';

export const mockAdminDashboardData: AdminDashboardData = {
  stats: {
    totalUsers: 1847,
    totalStudents: 1602,
    totalTutors: 245,
    totalCourses: 456,
    activeCourses: 398,
    pendingCourses: 23,
    totalRevenue: 4850000000,
    monthlyRevenue: 425000000,
    pendingTutorApplications: 12,
    pendingWithdrawals: 8,
    totalBookings: 3254,
    activeUsers: 892,
  },

  revenueChart: [
    { month: 'T1', revenue: 285000000, commission: 28500000 },
    { month: 'T2', revenue: 310000000, commission: 31000000 },
    { month: 'T3', revenue: 345000000, commission: 34500000 },
    { month: 'T4', revenue: 320000000, commission: 32000000 },
    { month: 'T5', revenue: 380000000, commission: 38000000 },
    { month: 'T6', revenue: 410000000, commission: 41000000 },
    { month: 'T7', revenue: 395000000, commission: 39500000 },
    { month: 'T8', revenue: 425000000, commission: 42500000 },
    { month: 'T9', revenue: 455000000, commission: 45500000 },
    { month: 'T10', revenue: 480000000, commission: 48000000 },
    { month: 'T11', revenue: 505000000, commission: 50500000 },
    { month: 'T12', revenue: 540000000, commission: 54000000 },
  ],

  userGrowthChart: [
    { month: 'T1', students: 128, tutors: 18 },
    { month: 'T2', students: 145, tutors: 22 },
    { month: 'T3', students: 162, tutors: 25 },
    { month: 'T4', students: 138, tutors: 19 },
    { month: 'T5', students: 175, tutors: 28 },
    { month: 'T6', students: 192, tutors: 31 },
    { month: 'T7', students: 168, tutors: 24 },
    { month: 'T8', students: 185, tutors: 27 },
    { month: 'T9', students: 205, tutors: 33 },
    { month: 'T10', students: 218, tutors: 35 },
    { month: 'T11', students: 232, tutors: 38 },
    { month: 'T12', students: 254, tutors: 42 },
  ],

  recentUsers: [
    {
      id: '1',
      fullName: 'Nguyễn Minh Anh',
      email: 'minhanh@email.com',
      avatar: 'https://i.pravatar.cc/150?img=1',
      role: 'student',
      joinedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      fullName: 'Trần Hải Đăng',
      email: 'haidang@email.com',
      avatar: 'https://i.pravatar.cc/150?img=2',
      role: 'tutor',
      joinedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '3',
      fullName: 'Lê Thùy Linh',
      email: 'thuylinh@email.com',
      avatar: 'https://i.pravatar.cc/150?img=3',
      role: 'student',
      joinedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '4',
      fullName: 'Phạm Quốc Tuấn',
      email: 'quoctuan@email.com',
      avatar: 'https://i.pravatar.cc/150?img=4',
      role: 'tutor',
      joinedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '5',
      fullName: 'Hoàng Mai Phương',
      email: 'maiphuong@email.com',
      avatar: 'https://i.pravatar.cc/150?img=5',
      role: 'student',
      joinedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '6',
      fullName: 'Vũ Đức Mạnh',
      email: 'ducmanh@email.com',
      avatar: 'https://i.pravatar.cc/150?img=6',
      role: 'student',
      joinedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
  ],

  recentCourses: [
    {
      id: '1',
      title: 'Tiếng Anh giao tiếp nâng cao cho doanh nhân',
      tutorName: 'Nguyễn Văn A',
      status: 'pending',
      submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      title: 'Tiếng Nhật cơ bản - JLPT N5',
      tutorName: 'Trần Thị B',
      status: 'pending',
      submittedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '3',
      title: 'Tiếng Hàn cho người mới bắt đầu',
      tutorName: 'Lê Minh C',
      status: 'approved',
      submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '4',
      title: 'Tiếng Trung HSK 3',
      tutorName: 'Phạm Thu D',
      status: 'approved',
      submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '5',
      title: 'Tiếng Pháp giao tiếp du lịch',
      tutorName: 'Hoàng Anh E',
      status: 'rejected',
      submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],

  platformActivities: [
    {
      id: '1',
      type: 'user_registered',
      description: 'Nguyễn Minh Anh đã đăng ký tài khoản học viên',
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      user: 'Nguyễn Minh Anh',
    },
    {
      id: '2',
      type: 'course_created',
      description: 'Trần Hải Đăng đã tạo khóa học "Tiếng Anh giao tiếp nâng cao"',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      user: 'Trần Hải Đăng',
    },
    {
      id: '3',
      type: 'booking_made',
      description: 'Lê Thùy Linh đã đặt lịch học 1-1 với tutor Phạm Quốc Tuấn',
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      user: 'Lê Thùy Linh',
    },
    {
      id: '4',
      type: 'payment_completed',
      description: 'Hoàng Mai Phương đã thanh toán 2.500.000đ cho khóa học',
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      user: 'Hoàng Mai Phương',
    },
    {
      id: '5',
      type: 'tutor_approved',
      description: 'Đơn đăng ký làm tutor của Vũ Đức Mạnh đã được phê duyệt',
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      user: 'Vũ Đức Mạnh',
    },
    {
      id: '6',
      type: 'course_created',
      description: 'Nguyễn Văn A đã tạo khóa học "Tiếng Nhật JLPT N4"',
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      user: 'Nguyễn Văn A',
    },
    {
      id: '7',
      type: 'user_registered',
      description: 'Trần Thị B đã đăng ký tài khoản tutor',
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      user: 'Trần Thị B',
    },
    {
      id: '8',
      type: 'payment_completed',
      description: 'Lê Minh C đã thanh toán 1.800.000đ cho gói học',
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      user: 'Lê Minh C',
    },
  ],

  topTutors: [
    {
      id: '1',
      fullName: 'Nguyễn Hoàng Anh',
      avatar: 'https://i.pravatar.cc/150?img=11',
      totalCourses: 15,
      totalStudents: 342,
      totalRevenue: 185000000,
      rating: 4.9,
    },
    {
      id: '2',
      fullName: 'Trần Minh Tuấn',
      avatar: 'https://i.pravatar.cc/150?img=12',
      totalCourses: 12,
      totalStudents: 298,
      totalRevenue: 156000000,
      rating: 4.8,
    },
    {
      id: '3',
      fullName: 'Lê Thu Hà',
      avatar: 'https://i.pravatar.cc/150?img=13',
      totalCourses: 10,
      totalStudents: 267,
      totalRevenue: 142000000,
      rating: 4.7,
    },
    {
      id: '4',
      fullName: 'Phạm Quốc Việt',
      avatar: 'https://i.pravatar.cc/150?img=14',
      totalCourses: 9,
      totalStudents: 234,
      totalRevenue: 128000000,
      rating: 4.8,
    },
    {
      id: '5',
      fullName: 'Hoàng Mai Linh',
      avatar: 'https://i.pravatar.cc/150?img=15',
      totalCourses: 8,
      totalStudents: 215,
      totalRevenue: 115000000,
      rating: 4.6,
    },
  ],
};
